from django.urls import path

from . import views

urlpatterns = [
    path('', views.first, name='first'),
    path('getstarted/', views.getstarted, name='getstarted'),
    path('getstarted.html', views.getstarted),
    path('login/', views.login_page, name='login'),
    path('login.html', views.login_page),
    path('logout/', views.logout_page, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard.html', views.dashboard),
    path('aptitude/', views.aptitude, name='aptitude'),
    path('aptitude.html', views.aptitude),
    path('coding/', views.coding, name='coding'),
    path('coding.html', views.coding),
    path('resume/', views.resume, name='resume'),
    path('resume.html', views.resume),
    path('mocktest/', views.mocktest, name='mocktest'),
    path('mocktest.html', views.mocktest),
    path('site-admin/login/', views.site_admin_login, name='site_admin_login'),
    path('site-admin/', views.site_admin_dashboard, name='site_admin_dashboard'),
    path('site-admin/tests/', views.site_admin_tests, name='site_admin_tests'),
    path('site-admin/tests/new/', views.site_admin_test_create, name='site_admin_test_create'),
    path('site-admin/tests/<int:test_id>/edit/', views.site_admin_test_update, name='site_admin_test_update'),
    path('site-admin/tests/<int:test_id>/delete/', views.site_admin_test_delete, name='site_admin_test_delete'),
    path('site-admin/questions/', views.site_admin_questions, name='site_admin_questions'),
    path('site-admin/questions/new/', views.site_admin_question_create, name='site_admin_question_create'),
    path('site-admin/questions/<int:question_id>/edit/', views.site_admin_question_update, name='site_admin_question_update'),
    path('site-admin/questions/<int:question_id>/delete/', views.site_admin_question_delete, name='site_admin_question_delete'),
    path('site-admin/coding-questions/', views.site_admin_coding_questions, name='site_admin_coding_questions'),
    path('site-admin/coding-questions/new/', views.site_admin_coding_question_create, name='site_admin_coding_question_create'),
    path('site-admin/coding-questions/<int:question_id>/edit/', views.site_admin_coding_question_update, name='site_admin_coding_question_update'),
    path('site-admin/coding-questions/<int:question_id>/delete/', views.site_admin_coding_question_delete, name='site_admin_coding_question_delete'),
    path('tests/<int:test_id>/start/', views.start_test, name='start_test'),
    path('attempts/<int:attempt_id>/take/', views.take_aptitude_test, name='take_aptitude_test'),
    path('attempts/<int:attempt_id>/result/', views.aptitude_result, name='aptitude_result'),
    path('attempts/<int:attempt_id>/coding/take/', views.take_coding_test, name='take_coding_test'),
    path('attempts/<int:attempt_id>/coding/run/', views.run_code, name='run_code'),
    path('attempts/<int:attempt_id>/coding/submit_code/', views.submit_code, name='submit_code'),
    path('attempts/<int:attempt_id>/coding/submit_exam/', views.submit_coding_exam, name='submit_coding_exam'),
    path('attempts/<int:attempt_id>/coding/result/', views.coding_result, name='coding_result'),
    path('first.html', views.first),
]
