# Generated by Django 6.0.5 on 2026-05-22 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_testattempt_correct_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('sample_input', models.TextField(blank=True)),
                ('sample_output', models.TextField(blank=True)),
                ('test_cases', models.JSONField(blank=True, default=list)),
                ('starter_code_python', models.TextField(blank=True)),
                ('starter_code_java', models.TextField(blank=True)),
                ('starter_code_cpp', models.TextField(blank=True)),
                ('starter_code_c', models.TextField(blank=True)),
                ('starter_code_js', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='myapp.preptest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('code', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=40)),
                ('passed_cases', models.PositiveIntegerField(default=0)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to='myapp.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='myapp.codingquestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='codingquestion',
            constraint=models.UniqueConstraint(fields=('test', 'order'), name='unique_coding_question_order_per_test'),
        ),
    ]
